# Generated by Django 4.1 on 2022-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='pool_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='sea_view',
            field=models.BooleanField(default=False),
        ),
    ]
