# Generated by Django 4.1 on 2022-08-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='admin',
            new_name='is_active',
        ),
    ]
